---
deployment:
  tasks:
    - export:
        name: DEPLOYPATH
        value: /home/expresionary/public_html/
    - command: mkdir -p "$DEPLOYPATH"
    - command: /bin/cp -a dist/. "$DEPLOYPATH"
    - export:
        name: DEPLOYSERVER
        value: /home/expresionary/server
    - command: mkdir -p "$DEPLOYSERVER"
    - command: /bin/cp -a server/dist/. "$DEPLOYSERVER"
