---
deployment:
  tasks:
    # path on the cPanel server where the frontend build should be deployed
    - export DEPLOYPATH=/home/expresionary/public_html/
    - mkdir -p "$DEPLOYPATH"
    # copy the frontend build output (dist) into the public_html folder
    - /bin/cp -a dist/. "$DEPLOYPATH"
