---
deployment:
  tasks:
    - export DEPLOYPATH=/home/expresionary/public_html/
    - mkdir -p "$DEPLOYPATH"
    - /bin/cp -a dist/. "$DEPLOYPATH"
    - mkdir -p "$DEPLOYPATH/../server"
    - /bin/cp -a server/dsit/. "$DEPLOYPATH/../server"